# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8635dc5b3ea44e2837aa7c2c395a38a51e07a0f7091c7e0b659f624509ec3d1c3d3146b2ace67ac4a53e1a1028a0454827c24a738021fd1c8df5a3ab85ae5cc2

test:
  secret_key_base: fc2be197a9d5b76bed514c19eb719cbe456e4cd4dcc4428f3a9f8874d009263dfec2b4b83c41a76659f7670aa0c689c2dcc7e6092e2fc441148d4b94e556502c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
